cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove


app_name = "cart"
urlpatterns = [
    path('add/<int:product_id>/', cart_add, name="cart_add"),
    path("",cart_detail, name="cart_detail"),
    path("remove/<int:product_id>/", cart_remove, name="remove_item")
]

ecommercesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include('cart.urls')),
    path("orders/", include("orders.urls")),
    path('', include('products.urls', namespace='products')),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create, order_confirmation

app_name = "orders"

urlpatterns = [
    path('create', order_create, name="order_create"),
    path("confirmation/<int:order_id>", order_confirmation, name="order_confirmation"),
]

products/urls.py
from django.urls import path
from . import views


app_name= 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

cart/models.py
from django.db import models
from products.models import Product


class Cart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    
    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all())

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="cart_items", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    
    def get_total_price(self):
        return self.product.price * self.quantity
    

orders/models.py
from django.db import models
from products.models import Product

class Order(models.Model):
    full_name = models.CharField(max_length=250)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def get_cost(self):
        return self.price * self.quantity

products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "categories"
    
    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products', blank=True, null=True)
    
    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'id':self.id, 'slug':self.slug})
    
        
    
    

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["full_name", "email", "address"]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from products.models import Product
from .models import Cart, CartItem
from django.views.decorators.http import require_POST
from django.http import JsonResponse

@require_POST
def cart_add(request, product_id):
    cart_id = request.session.get('cart_id')
    
    if cart_id:
        try:
            cart = Cart.objects.get(id=cart_id)
        except Cart.DoesNotExist:
            cart = Cart.objects.create()
    else:
        cart = Cart.objects.create()
        request.session['cart_id'] = cart.id
    
    product = get_object_or_404(Product, id=product_id)
    
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    if not created:
        cart_item.quantity += 1
    
    cart_item.save()
    
    response_data = {
        "success":True,
        "message": f'Added {product.name} to cart'
    }
    
    return JsonResponse(response_data)
    
    
def cart_detail(request):
    cart_id = request.session.get('cart_id')
    cart=None
    
    if cart_id:
        cart = get_object_or_404(Cart, id=cart_id)
    if not cart or not cart.items.exists():
        cart=None
    
    return render(request, "cart/detail.html", {"cart":cart})
    
def cart_remove(request, product_id):
    cart_id = request.session.get('cart_id')
    cart = get_object_or_404(Cart, id=cart_id)
    item = get_object_or_404(CartItem, id=product_id, cart=cart)
    item.delete()
    
    return redirect("cart:cart_detail")

    

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import Cart
from .forms import OrderCreateForm
from .models import OrderItem, Order



def order_create(request):
    cart=None
    cart_id = request.session.get('cart_id')
    
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
        
        if not cart or not cart.items.exists():
            return redirect("cart:cart_detail")
    
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.save()
            
            for item in cart.items.all():
                OrderItem.objects.create(
                    order = order,
                    product = item.product,
                    price = item.product.price,
                    quantity = item.quantity
                )
            cart.delete()
            del request.session["cart_id"]
            return redirect("orders:order_confirmation", order.id)
        else:
            form = OrderCreateForm()
            
        return render(request, "orders/order_create.html", {
            "cart":cart, "form":form
        })

def order_confirmation(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "orders/order_confirmation.html", {"order":order})

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    category = None
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    return render(request, 'products/product/list.html', {
        'category':category,
        'products':products,
        'categories':categories,
    })
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'products/product/detail.html', {'product':product})

cart/templates/cart/detail.html
{% extends "base.html" %}
{%block title%}My Cart{%endblock%}


{%block content%}
<h2 class="text-2xl font-semibold mb-4">My Cart</h2>

{%if cart %}
<ul class="space-y-4">
    {%for item in cart.items.all %}
    <li class="flex items-center p-4">
        {%if item.product.image%}
        <img src="{{item.product.image.url}}" alt={{item.product.name}} class="w-24 mr-4">
        {%endif%}
        <div class="flex-grow">
            <a href="{%url 'products:product_detail' item.product.id item.product.slug%}">
        <h3 class="font-semibold text-lg">{{item.product.name}}</h3>
            </a>
        <p class="text-gray-700">{{item.product.description}}</p>
        <p class="text-indigo-600">${{item.product.price}}</p>
        <p class="text-gray-600">Quantity: {{item.quantity}}</p>

<div class="flex-shrink">
   <form action="{%url 'cart:remove_item' item.id %}"  method="post">
    {%csrf_token%}
    <button type="submit" class="bg-red-600 text-white px-4 py-1 text-xs rounded">X</button>
   </form>
</div>
        </div>
    </li>
    {%endfor%}
</ul>

<p><strong>Total Price: ${{cart.get_total_price}}</strong></p>
{%else%}
<p>Your Cart is empty.</p>
{% endif %}
<form action="{% url 'orders:order_create'%}" method="post">
    {%csrf_token%}
    <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded mt-0.5">Proceed to Checkout</button>
</form>
{%endblock%}

orders/templates/orders/order_confirmation.html
{% extends "base.html" %}
{%block title%}Order Confirmation{%endblock%}


{%block content%}

<h2>Your order has been placed! Below are the details.</h2>

<h3>Order ID: #{{order.id}}</h3>
<ul>
    {%for item in order.items.all%}
    <li>
        <strong>{{item.quantity}} x {{item.product.name}}</strong>
        <br>
        <span>{{item.price}}</span>

    </li>
    {%endfor%}
    <ul>

        <p>Total" ${{order.get_total_cost}}</p>
{%endblock%}

orders/templates/orders/order_create.html
{% extends "base.html" %}
{%block title%}Order Create{%endblock%}



{%block content%}
<div class="shadow-md p-4">
    <h2 class="text-indigo-600 text-2xl font-semibold mb-4">Checkout</h2>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button  class="bg-indigo-600 text-white px-4 py-2 rounded mt-0.5" type="submit">Place Order</button>
    </form>
</div>

<style>
    form p{
       margin-bottom: 1rem;
    }
</style>
{%endblock%}

products/templates/products/product/detail.html
{% extends "base.html" %}

{%block title%}{{product.name}}{%endblock%}

{%block content%}
<div class="container mx-auto p-4 flex">

<div>
    {%if product.image%}
    <img src="{{product.image.url}}" alt={{product.name}} class="max-h-[80vh]">
    {%else%}
    <p>The image is not available</p>
    {%endif%}
    <h3 class="font-semibold">{{product.name}}</h3>
    <p>{{product.description}}</p>
    <p class="text-indigo-600">${{product.price}}</p>

    <form action="{%url 'cart:cart_add' product.id%}" method="post" id="add-to-cart-form">
        {% csrf_token %}
        <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded">Add to cart</button>
    <p id="message"></p>
    </form>
</div>



</div>

<script>
    document.getElementById('add-to-cart-form').addEventListener("submit", function(event){
        event.preventDefault();

        const form = event.target;
        const url = form.action;
        const formData = new FormData(form);

        fetch(url, {
            method:'POST',
            headers:{
                'X-CSRFToken':formData.get('csrfmiddlewaretoken')
            },
            body: formData
        })
        .then(response => response.json())
        .then(data=>{
            const messageElement = document.getElementById('message');
            if (data.success){
                messageElement.textContent = data.message;
            }else{
                message.textContent = "Failed to add to cart";
            }
        })
        .catch(error=>{
            console.error("Error", error);
        })
    })
</script>
    {%endblock%}

products/templates/products/product/list.html
{% extends "base.html" %}

{%block title%}My site{%endblock%}

{%block content%}

<div class="container mx-auto p-4 flex">
    <aside class="w-1/4 p-4">
        <h2 class="font-bold">Categories:</h2>
        <ul>
            {%for category in categories%}
            <li>
                <a href="{% url 'products:product_list_by_category' category.slug %}">{{category.name}}</a>
            </li>
            {%endfor%}
            
        </ul>
    </aside>
    <main class="w-3/4 p-4">
        {%if category%}
        <h2 class="font-bold mb-4">{{category.name}}</h2>
        {%else%}
        <h2 class="font-bold mb-4">All Products:</h2>

        {%endif%}
        <div class="grid grid-cols-3 gap-4">
            {% for product in products %}
            <a href="{% url 'products:product_detail' product.id product.slug %}">
            <div>
                {% if product.image %}
                <img src="{{product.image.url}}" alt={{product.name}} class="h-64 w-44 object-cover">
                {%else%}
                <p>The image is not available</p>
                {%endif%}

                <h3 class="font-semibold">{{product.name}}</h3>
                <p>{{product.description}}</p>
                <p class="text-indigo-600">${{product.price}}</p>
            </div>
        </a>
            {%endfor%}

        </div>
    </main>
    
</div>

{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>{%block title%}My Super Cool Shop Site{%endblock%}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1" />
		{% load static %}
		<link href="{% static 'dist/styles.css'%}" rel="stylesheet" />
		<meta name="description" content="" />
		<link rel="icon" href="favicon.png" />
	</head>
	<body class="bg-gray-100 text-gray-800 flex flex-col min-h-screen">
		<header class="shadow-md">{% include "includes/nav.html" %}</header>

		<main class="container mx-auto py-8 flex-grow">
			{%block content%}{%endblock%}
		</main>

		<footer>
			<div class="container mx-auto p-4 text-center">
				<p>@2024 E-Com Inc. All rights reserved.</p>
			</div>
		</footer>
	</body>
</html>

templates/includes/nav.html
<nav class="container mx-auto p-4 flex justify-between items-center">
    <a href='/' class="text-2xl font-bold text-indigo-600">E-Com</a>

<a href="{% url 'cart:cart_detail'%}">
    <svg class="w-8" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="36px" viewBox="0 0 40 36" style="enable-background:new 0 0 40 36;" xml:space="preserve">
<g id="Page-1_4_" sketch:type="MSPage">
	<g id="Desktop_4_" transform="translate(-84.000000, -410.000000)" sketch:type="MSArtboardGroup">
		<path id="Cart" sketch:type="MSShapeGroup" class="st0" d="M94.5,434.6h24.8l4.7-15.7H92.2l-1.3-8.9H84v4.8h3.1l3.7,27.8h0.1
			c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h12.8c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h1.7v-3.9l-25.8-0.1L94.5,434.6"
			/>
	</g>
</g>
  </svg>
</a>
</nav>